const router = require("express").Router();
const protect = require("../../middlewares/auth.middleware");
const checkRole = require("../../middlewares/role.middleware");
const brandAdminRoutes = require("./brand.admin.route");
const categoryAdminRoutes = require("./category.admin.route");
const productAdminRoutes = require("./product.admin.route");
const orderAdminRoutes = require("./order.admin.route");
const couponAdminRoutes = require("./coupon.admin.route");
const saleAdminRoutes = require("./sale.admin.route");
const dashboardAdminRoutes = require("./dashboard.admin.route");
router.use(protect, checkRole("admin"));
router.use("/brands", brandAdminRoutes);
router.use("/categories", categoryAdminRoutes);
router.use("/products", productAdminRoutes);
router.use("/orders", orderAdminRoutes);
router.use("/coupons", couponAdminRoutes);
router.use("/sales", saleAdminRoutes);
router.use("/dashboard", dashboardAdminRoutes);
module.exports = router;
