// Accessories data for the AccessoriesPage
// Images reuse the existing AccessoriesSection assets from the HomePage

export const allAccessories = [
  {
    id: 1,
    name: "Sport Band 44mm",
    category: "straps",
    price: "590,000",
    rating: "4.9",
    reviews: "350",
    image: "/HomePage/AccessoriesSection/watch-straps.png",
  },
  {
    id: 2,
    name: "Magnetic Charging Dock",
    category: "docks",
    price: "450,000",
    rating: "5.0",
    reviews: "220",
    image: "/HomePage/AccessoriesSection/charging-dock.png",
  },
  {
    id: 3,
    name: "Tempered Screen Guard",
    category: "guards",
    price: "120,000",
    rating: "4.8",
    reviews: "180",
    image: "/HomePage/AccessoriesSection/screen-guard.png",
  },
  {
    id: 4,
    name: "Premium Storage Pouch",
    category: "pouches",
    price: "250,000",
    rating: "4.7",
    reviews: "150",
    image: "/HomePage/AccessoriesSection/storage-pouch.png",
  },
  {
    id: 5,
    name: "Complete Accessory Bundle",
    category: "bundles",
    price: "990,000",
    rating: "5.0",
    reviews: "410",
    image: "/HomePage/AccessoriesSection/accessory-bundle.png",
  },
  {
    id: 6,
    name: "USB-C Replacement Cable",
    category: "cables",
    price: "180,000",
    rating: "4.6",
    reviews: "290",
    image: "/HomePage/AccessoriesSection/replacement-cable.png",
  },
  {
    id: 7,
    name: "Leather Milanese Loop",
    category: "straps",
    price: "780,000",
    rating: "4.9",
    reviews: "125",
    image: "/HomePage/AccessoriesSection/watch-straps.png",
  },
  {
    id: 8,
    name: "Dual Charging Dock Pro",
    category: "docks",
    price: "680,000",
    rating: "4.8",
    reviews: "95",
    image: "/HomePage/AccessoriesSection/charging-dock.png",
  },
  {
    id: 9,
    name: "3-Pack Screen Guard Set",
    category: "guards",
    price: "199,000",
    rating: "4.7",
    reviews: "340",
    image: "/HomePage/AccessoriesSection/screen-guard.png",
  },
];
